### ISSUE TITLE
What is the purpose of export { mapDispatchToProps }

### ISSUE THREAD

**Issue by ejabu** [flexdinesh/react-redux-boilerplate#14]
I wrote a comment here on [the commit diff ](https://github.com/flexdinesh/react-redux-boilerplate/commit/04829f8dd5deffb695aef966585a39f7ed68692e#diff-b40dc3de2b66cf46597584200a5599f7)

What is the purpose of export { mapDispatchToProps };

As I can leave that line in another container

best regards

@flexdinesh

**Comment by flexdinesh** [comment]
@ejabu It's completely okay to not export `mapDispatchToProps `. The reason we're exporting it is because only then we'll be able to test the method in [our test file here](https://github.com/flexdinesh/react-redux-boilerplate/blob/5ec626d9ae6b9541fe94afa393e20942062a28ef/app/containers/HomePage/tests/index.test.js#L54).
