### ISSUE TITLE
Webpack compile error after fresh git clone, npm install, then npm start

### ISSUE THREAD

**Issue by shahrin-14** [flexdinesh/react-redux-boilerplate#18]
I did a git clone, with no changes to the code.

I ran npm install, no problems. Then I started the server using npm start. The console shows the following error:

```sh
ERROR in ./app/components/Header/images/banner.jpg
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: write EOF
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
 @ ./app/components/Header/Header.js 11:0-41 33:44-50
 @ ./app/components/Header/index.js
 @ ./app/containers/App/App.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
i ｢wdm｣: Failed to compile.
```

Hope for some pointers.

**Comment by basselAhmed** [comment]
Same here

**Comment by maa105** [comment]
it seems he forgot to upload banner,jpg just comment:
import Banner from './images/banner.jpg';
AND
<img src={Banner} alt="react-redux-boilerplate - Logo" />
from
./app/components/Header/Header.js

**Comment by flexdinesh** [comment]
@maa105 The image is in the dir `components/Header/images/banner.jpg`. 

The issue is most like related to `image-webpack-loader` which is known to have inconsistencies between machines due to its OS dependencies. This is more likely to happen in Linux environment.

If you're in a Linux environment, this command might help,
`sudo apt-get install libpng16-dev`
